[Desktop Entry]
Encoding=UTF-8
Type=Service
Exec=blubb
Comment=CSS Language Support
Comment[bs]=Podrška za CSS jezik
Comment[cs]=Podpora jazyka CSS
Comment[de]=Sprachunterstützung für CSS
Comment[es]=Implementación del lenguaje CSS
Comment[et]=CSS keele toetus
Comment[fi]=CSS-kielituki
Comment[fr]=Prise en charge du langage CSS
Comment[ga]=Tacaíocht Teanga CSS
Comment[gl]=Compatibilidade coa linguaxe CSS
Comment[hu]=CSS nyelvi támogatás
Comment[nl]=Taalondersteuning voor CSS
Comment[pl]=Obsługa języka CSS
Comment[pt]=Suporte para a Linguagem CSS
Comment[pt_BR]=Suporte à linguagem CSS
Comment[sk]=Podpora jazyka CSS
Comment[sv]=Språkstöd för CSS-språk
Comment[tr]=CSS Dil Desteği
Comment[uk]=Підтримка мови CSS
Comment[x-test]=xxCSS Language Supportxx
Name=KDevCssSupport
Name[bs]=KDevCssSupport
Name[cs]=KDevCssSupport
Name[de]=KDevCssSupport
Name[es]=KDevCssSupport
Name[et]=KDevCssSupport
Name[fi]=KDevCssSupport
Name[fr]=KDevCssSupport
Name[ga]=KDevCssSupport
Name[gl]=KDevCssSupport
Name[hu]=KDevCssSupport
Name[it]=KDevCssSupport
Name[nl]=KDevCssSupport
Name[pl]=ObsługaKDevCss
Name[pt]=KDevCssSupport
Name[pt_BR]=KDevCssSupport
Name[sk]=KDevCssSupport
Name[sv]=KDevelop CSS-stöd
Name[tr]=KDevCssSupport
Name[uk]=KDevCssSupport
Name[x-test]=xxKDevCssSupportxx
GenericName=CSS Support
GenericName[bs]=Podrška za CSS
GenericName[cs]=Podpora CSS
GenericName[de]=CSS-Unterstützung
GenericName[es]=Implementación de CSS
GenericName[et]=CSS-i toetus
GenericName[fi]=CSS-tuki
GenericName[fr]=Prise en charge de CSS
GenericName[ga]=Tacaíocht CSS
GenericName[gl]=Compatibilidade con CSS
GenericName[hu]=CSS támogatás
GenericName[nl]=CSS-ondersteuning
GenericName[pl]=Obsługa CSS
GenericName[pt]=Suporte para CSS
GenericName[pt_BR]=Suporte à CSS
GenericName[sk]=Podpora CSS
GenericName[sv]=CSS-stöd
GenericName[tr]=CSS Desteği
GenericName[ug]=CSS قوللىشى
GenericName[uk]=Підтримка CSS
GenericName[x-test]=xxCSS Supportxx
ServiceTypes=KDevelop/Plugin
Icon=source
X-KDE-Library=kdevcsslanguagesupport
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Language=Css
X-KDevelop-Args=CSS
X-KDevelop-Interfaces=ILanguageSupport
X-KDevelop-SupportedMimeTypes=text/css,text/html
X-KDE-PluginInfo-Name=KDevCssSupport
X-KDevelop-Mode=NoGUI
X-KDevelop-LoadMode=AlwaysOn
