// THIS FILE IS GENERATED
// WARNING! All changes made in this file will be lost!
#ifndef KDEVCSS_VERSION_H
#define KDEVCSS_VERSION_H

#include <kdeversion.h>

#define KDEVCSS_MAJOR_VERSION @VERSION_MAJOR@
#define KDEVCSS_MINOR_VERSION @VERSION_MINOR@
#define KDEVCSS_PATCH_VERSION @VERSION_PATCH@

#define KDEVCSS_VERSION_STR "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_PATCH@"

#define KDEVCSS_VERSION KDE_MAKE_VERSION(@VERSION_MAJOR@, @VERSION_MINOR@, @VERSION_PATCH@)

#endif
