// THIS FILE IS GENERATED
// WARNING! All changes made in this file will be lost!
#ifndef KDEVCSS_VERSION_H
#define KDEVCSS_VERSION_H

#include <kdeversion.h>

#define KDEVCSS_MAJOR_VERSION @KDEVCSS_VERSION_MAJOR@
#define KDEVCSS_MINOR_VERSION @KDEVCSS_VERSION_MINOR@
#define KDEVCSS_PATCH_VERSION @KDEVCSS_VERSION_PATCH@

#define KDEVCSS_VERSION_STR "@KDEVCSS_VERSION_MAJOR@.@KDEVCSS_VERSION_MINOR@.@KDEVCSS_VERSION_PATCH@"

#define KDEVCSS_VERSION KDE_MAKE_VERSION(@KDEVCSS_VERSION_MAJOR@, @KDEVCSS_VERSION_MINOR@, @KDEVCSS_VERSION_PATCH@)

#endif
